### ISSUE TITLE
Version 0.5.3 broking listeners for keyboard events (?)

### ISSUE THREAD

**Issue by alphamikle** [adee42/flutter_keyboard_visibility#13]
Hi, i just update to 0.5.3 version and explore this bug.
In short words: in 0.5.2 it's works fine, but in 0.5.3 - listeners not working
detailed video with code example and emulator screen at https://youtu.be/Brh8pCvXcw4 (if quality is bad - wait several hours while youtube is upload a high quality of video)

**Comment by adee42** [comment]
Yes, I experienced the same problem now. I fixed it and uploaded a new version 0.5.4 that fixes the bug. Please try it and thanks for the detailed description!
