### ISSUE TITLE
not work for the 1st time.

### ISSUE THREAD

**Issue by seu1902** [adee42/flutter_keyboard_visibility#14]
Hey, I'm new here. Today I simply git clone the code, and then run the example. No code has been changed.

It didn't work at the fist time, no matter how many times I toggled the keyboard.

But strangely, when I quited the app and entered it again, it worked!

Here's the flutter doctor msg:

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

**Comment by adee42** [comment]
If you tried ver. 0.5.3 then it might not work as it is broken. Can you try if the same behavior occurs with ver. 0.5.4 that I uploaded only a few moments ago?

**Comment by seu1902** [comment]
It worked now, thanks!
