### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by micajuine-ho** [adee42/flutter_keyboard_visibility#3]
Hey man,

Thank you for making this package, I am really excited to use it.
Unfortunately, the package throws a MissingPluginException: 

`The following MissingPluginException was thrown while activating platform stream on channel github.com/adee42/flutter_keyboard_visibility:

MissingPluginException(No implementation found for method listen on channel github.com/adee42/flutter_keyboard_visibility)`

I cloned your repo, added it to my project and updated my dependencies. Any idea on why this is happening?

**Comment by adee42** [comment]
Hi man,

you are welcome. I'll take a guess here and say that you copied the files into your project directly without using the pubspec.yaml file. If you want to integrate this directly, you also have to add a few lines to the native code to register the plugin (this is something that Flutter does automatically when you include it in the pubspecs).

For Android you have to add the following line in the MainActivity.java file (I usually do it above the GeneratedPluginRegistrant.registerWith(this); - line):
KeyboardVisibilityPlugin.registerWith(this.registrarFor("com.github.adee42.keyboardvisibility"));

For iOS you have to add the following line in the AppDelegate.m file:
[KeyboardVisibilityHandler registerWithRegistrar:[self registrarForPlugin:@"com.github.adee42.keyboardvisibility"]];

If you didn't copy the files directly, please let me know how you included this plugin into your pubspec.yaml file.

**Comment by micajuine-ho** [comment]
Ahh thank you, I got it working!

I was wondering if there was a better way to use this package, other than cloning it and having the code directly in my project.

Thanks again.

**Comment by diego-lipinski-de-castro** [comment]
I installed this plugin via the yaml file and got the same error

**Comment by diego-lipinski-de-castro** [comment]
It seems that fully stopping the application and re-running it solves the problem, this is an important note, should be on the readme I think, it wont work if you only refresh the app after getting the package, you need to fully restart your app

**Comment by Leeeeerich** [comment]
Hi! I have same problem, but i use pubspec.yaml and it not work((( 

Then i added:

``` For Android you have to add the following line in the MainActivity.java file (I usually do it above the GeneratedPluginRegistrant.registerWith(this); - line):
KeyboardVisibilityPlugin.registerWith(this.registrarFor("com.github.adee42.keyboardvisibility"));

For iOS you have to add the following line in the AppDelegate.m file:
[KeyboardVisibilityHandler registerWithRegistrar:[self registrarForPlugin:@"com.github.adee42.keyboardvisibility"]]; ```

And not worked it!

**Comment by remoteportal** [comment]
Completely re-starting app did not help:

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel flutter_keyboard_visibility:
MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)

When the exception was thrown, this was the stack: 
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:517:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:64)
#8      new KeyboardVisibilityNotification (package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart:37:10)
...

**Comment by lewisMachilika** [comment]
For me stopping and starting the app worked

**Comment by Nike682631** [comment]
```MissingPluginException (MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility))```
I'm facing the above issue when writing integration test for my app.

**Comment by bradfrizzell** [comment]
I am also facing the same issue in my integration test

**Comment by davestimpert** [comment]
> I am also facing the same issue in my integration test

@bradfrizzell Did you find a solution?

**Comment by davestimpert** [comment]
@bradfrizzell this got me around the issue:

```
class _KeyboardVisibilityBuilder extends StatelessWidget {
  final Widget Function(BuildContext, bool) builder;

  const _KeyboardVisibilityBuilder({required this.builder});

  @override
  Widget build(BuildContext context) {
    if (Platform.environment.containsKey('FLUTTER_TEST')) {
      return builder(context, false);
    }
    return KeyboardVisibilityBuilder(builder: builder);
  }
}
```

**Comment by Ahmadjazzfrontend** [comment]
I’m also experiencing the same issue with `flutter_keyboard_visibility_plus`.

Environment:

* Flutter: 3.44.4 (stable)
* Dart: 3.12.2
* Platforms: Android and iOS
* Occurs in: Production

Error:
`MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)`

This issue is being reported through Firebase Crashlytics in our production app. It happen consistently, 

Could you please investigate this? It would be helpful to understand what could cause the plugin registration/native implementation to be unavailable at runtime in production.
