### ISSUE TITLE
I can't get apk after i added "keyboard_visibility: ^0.5.6" into pubspec.yaml

### ISSUE THREAD

**Issue by kadirbekar** [adee42/flutter_keyboard_visibility#49]
PS C:\Users\daydreamer\KaynakKodlari> flutter build apk --release  --build-name=1.1.3 --build-number=2
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\src\flutter\flutter_windows_v1.5.4-hotfix.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Removed unused resources: Binary resource data reduced from 70KB to 60KB: Removed 13%

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':keyboard_visibility:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\a1e87f5443b1512d74d302dbaa8fc6ba\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\a1e87f5443b1512d74d302dbaa8fc6ba\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 46s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      46,6s
Removed unused resources: Binary resource data reduced from 70KB to 60KB: Removed 13%

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':keyboard_visibility:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\a1e87f5443b1512d74d302dbaa8fc6ba\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\a1e87f5443b1512d74d302dbaa8fc6ba\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 46s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      46,6s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    5,0s
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 4s

The plugin connectivity could not be built due to the issue above.

Normally when i connect my phone to the pc there is no problem with this library but when i try to get apk like "flutter build apk --release" it shows the error.

And it does not work in ios real device.

**Comment by HarrisonQi** [comment]
+1

**Comment by vualeks** [comment]
Fixed it [here](https://github.com/adee42/flutter_keyboard_visibility/pull/51), although maybe others already fixed it. Shame this library is abandoned.

**Comment by daydreamer54** [comment]
When i had this error i had to solve my problem as soon as i can but it was not possible that's why i stop using this package. So far i did not use this package but right now to close this issue i wanted to use it again but when i try to get apk i gives me this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':keyboard_visibility:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: 
resource android:attr/fontVariationSettings not found.

     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: 
resource android:attr/ttcIndex not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s

It fixed and work for some of us here #46881 (i didn't try)

**Comment by daydreamer54** [comment]
When i had this error i had to solve my problem as soon as i can but it was not possible that's why i stop using this package. So far i did not use this package but right now to close this issue i wanted to use it again but when i try to get apk i gives me this error:

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':keyboard_visibility:verifyReleaseResources'.

    A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
    Android resource linking failed
    C:\Users\daydreamer.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error:
    resource android:attr/fontVariationSettings not found.

 C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: 

resource android:attr/ttcIndex not found.

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s

It fixed and work for some of us here: When i had this error i had to solve my problem as soon as i can but it was not possible that's why i stop using this package. So far i did not use this package but right now to close this issue i wanted to use it again but when i try to get apk i gives me this error:

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':keyboard_visibility:verifyReleaseResources'.

    A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
    Android resource linking failed
    C:\Users\daydreamer.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error:
    resource android:attr/fontVariationSettings not found.

 C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: 

resource android:attr/ttcIndex not found.

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s

It fixed and work for some of us here : https://github.com/flutter/flutter/issues/46881
I didn't try

**Comment by kadirbekar** [comment]
When i had this error i had to solve my problem as soon as i can but it was not possible that's why i stop using this package. So far i did not use this package but right now to close this issue i wanted to use it again but when i try to get apk i gives me this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':keyboard_visibility:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: 
resource android:attr/fontVariationSettings not found.

     C:\Users\daydreamer\.gradle\caches\transforms-2\files-2.1\9611c12a11fb129c2d552e558222aed1\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: 
resource android:attr/ttcIndex not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s

It fixed and work for some of us: https://github.com/flutter/flutter/issues/46881
I didn't try
