### ISSUE TITLE
Change DidShow to WillShow

### ISSUE THREAD

**Issue by quetool** [adee42/flutter_keyboard_visibility#9]
Hi, in your plugin you use DidShow, and WillHide

```
[center addObserver:self selector:@selector(didShow) name:UIKeyboardDidShowNotification object:nil];
[center addObserver:self selector:@selector(didHide) name:UIKeyboardWillHideNotification object:nil];
```

Could be possible to change `UIKeyboardDidShowNotification` with `UIKeyboardWillShowNotification` in order to make consistent with WillHide? Or maybe add it? Thanks!

**Comment by adee42** [comment]
Hi, do you mean just the name of the function?

**Comment by quetool** [comment]
Hi @adee42, on iOS you have UIKeyboardDidShowNotification (Did) for when te keyboard is fully showed and UIKeyboardWillShowNotification (Will) for when the keyboard begins to show...
Generally is better to have the second one like in order to start scrolling the screen at the same time with the keyboard. It is just a suggestion

**Comment by adee42** [comment]
Thanks, I added it in ver. 0.5.2 of the plugin now. Thus Android doesn't support any information about the soft keyboard popping up, I didn't add a new message to the Dart file. It simply sends an additional message before the keyboard starts appearing

**Comment by quetool** [comment]
So, onShow now it's triggered by UIKeyboardDidShowNotification on iOS? Or by both?

**Comment by quetool** [comment]
Thanks, I just saw it on iOS files!
